spring:
  application:
    name: client

server:
  port: 8085
  servlet:
    context-path: /
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:WannaBeIn3ureka@localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 10000
    eureka-server-read-timeout-seconds: 10000

vaadin:
  async-supported: true